### ISSUE TITLE
Display a quote in the loading screen

### ISSUE THREAD

**Issue by michalove** [michalove/platformer#227]
This is just a little touch to make everything more ninja-like.

I suggest we replace the word "loading" in the loading screen by some clever quotation. Maybe something said by Konfuzius or a Japanese proverb:
http://en.wikipedia.org/wiki/Japanese_proverbs

Or maybe we implement a couple of them and one is randomly chosen on start up.

**Comment by Germanunkol** [comment]
I had this in a "Glückskeks" the other day:

"Der Frosch im Brunnen ahnt nichts von der Weite des Meeres."
- Japanische Weisheit

I thought I'd put it here, it somewhat fits the theme (but not perfectly). So if you were still looking for quotes, feel free to use this. Otherwise, please ignore this post.

For example as:
"The frog in the well has no clue about the vastness of the sea."

**Comment by michalove** [comment]
I found this translation: "A frog in a well does not know the great sea" and added it to the proverbs. Also I added some more and removed some. The new ones tend more towards funny.
